export const ADD_TODO = "ADD_TODO";

export const DELETE_TODO = "DELETE_TODO";

export const UPDATE_TODO = "UPDATE_TODO";

export const ADD_TO_ACTIVITY_LOG = "ADD_TO_ACTIVITY_LOG";

export const UPDATE_TOTAL_POINTS = "UPDATE_TOTAL_POINTS";

export const UPDATE_STATUS_TODO = "UPDATE_STATUS_TODO";

export const RESET_TASKS_TODO = "RESET_TASKS_TODO"; // SPRINT 04
